
--#region npc
-- function public.InitializeNPC(npcName, godType, params)
-- 	if not modstate.initialized then
-- 		rom.log.error("You must first Initialize your plugin guid, please use `GodsAPI.Initialize`")
-- 	end

-- 	if not npcName then
-- 		rom.log.error("InitializeGod: Missing required parameters `npcName`")
-- 	end

-- 	local baseGod = {
-- 		Name = "NPC_" .. npcName .. "_01",
-- 		Groups = { "NPCs" },
-- 		DamageType = "Neutral",

-- 		LoadPackages = params.LoadPackages or {}, -- Need it for the animations for in person

-- 		RepulseOnMeleeInvulnerableHit = params.RepulseOnMeleeInvulnerableHit or 150,
-- 		RarityUpgradeVoiceLines = params.RarityUpgradeVoiceLines or { [1] = { GlobalVoiceLines = "ZagreusRarifyVoiceLines" } },

-- 		NarrativeTextColor = params.NarrativeTextColor or { 32, 32, 30, 255 },
-- 		NameplateSpeakerNameColor = params.NameplateSpeakerNameColor or game.Color.DialogueSpeakerNameOlympian,
-- 		NameplateDescriptionColor = params.NameplateDescriptionColor or { 145, 45, 90, 255 },
-- 		LightingColor = params.LightingColor or { 1, 0.91, 0.54, 1 },
-- 		LootColor = params.LootColor or { 255, 128, 32, 255 },
-- 		SubtitleColor = params.SubtitleColor or { 255, 255, 205, 255 },

-- 		UpgradeScreenOpenFunctionName = params.UpgradeScreenOpenFunctionName,
-- 		RequiredRoomInteraction = params.RequiredRoomInteraction or true,
-- 		Traits = params.Traits or {},

-- 		--
-- 		EmoteOffsetY = -320,
-- 		UpgradeScreenOpenSound = "/SFX/DionysusBoonWineLaugh",
-- 		BoxAnimation = "DialogueSpeechBubbleLight",
-- 		MenuTitle = "UpgradeChoiceMenu_Dionysus",
-- 		TreatAsGodLootByShops = true,
-- 		UpgradeSelectedSound = "/SFX/DionysusBoonChoice",
-- 		InteractTextLineSets = {},
-- 		Using = {
-- 			Animation = "DionysusLobProjectileSmoke",
-- 		},
-- 		AlwaysShowInvulnerabubbleOnInvulnerableHit = true,
-- 		AnimOffsetZ = 50,
-- 		FlavorTextIds = {
-- 			"DionysusUpgrade_FlavorText01",
-- 			"DionysusUpgrade_FlavorText02",
-- 			"DionysusUpgrade_FlavorText03",
-- 		},
-- 		InheritFrom = { "NPC_Neutral", "NPC_Giftable" },
-- 		Portrait = "Portrait_Dionysus_Default_01",
-- 		SpeakerName = "Dionysus",
-- 		UpgradeMenuOpenVoiceLines = {},
-- 		OnUsedFunctionName = "UseLoot",
-- 		BoxExitAnimation = "DialogueSpeechBubbleLightOut",
-- 		SimulationSlowOnHit = false,
-- 		EmoteOffsetX = -30,
-- 		UseShrineUpgrades = false,
-- 		RequireUseToGift = true,
-- 		PreEventFunctionName = "AngleNPCToHero",
-- 		Icon = "BoonSymbolDionysus",
-- 		SpecialInteractCooldown = 60,
-- 		ActivateRequirements = {},
-- 		CanBeFrozen = false,
-- 		AlwaysShowDefaultUseText = true,
-- 		InvincibubbleScale = 1.5,
-- 		BlockPolymorph = true,
-- 		UsePromptOffsetY = -80,
-- 		TriggersOnDamageEffects = false,
-- 		BlocksLootInteraction = false,
-- 		SpecialInteractGameStateRequirements = {
-- 			{
-- 				PathTrue = { "GameState", "UseRecord", "NPC_Dionysus_01" },
-- 			},
-- 		},
-- 		SpecialInteractFunctionName = "SpecialInteractSalute",
-- 		TriggersOnHitEffects = true,
-- 		DropItemsOnDeath = false,
-- 		BlockLifeSteal = true,
-- 		GiftTextLineSets = {},
-- 		CanReceiveGift = true,
-- 		UsePromptOffsetX = 50,
-- 		PostTextLineEvents = {
-- 			{
-- 				FunctionName = "PartnersChattingPresentation",
-- 				Threaded = true,
-- 			},
-- 		},
-- 		ManualRecordUse = true,
-- 		IgnoreAutoLock = true,
-- 		UpgradeAcquiredAnimation = "MelinoeSalute",
-- 		MaxHitShields = 5,
-- 		BlockWrathGain = true,
-- 		TurnInPlaceAnimation = "Dionysus_Turn",
-- 		HideLevelDisplay = true,
-- 		UpgradeAcquiredAnimationDelay = 1.2,
-- 		RecheckConversationOnLootPickup = true,
-- 		SkipModifiers = true,
-- 		SkipDamagePresentation = true,
-- 		SkipDamageText = true,
-- 		AggroMinimumDistance = 500,
-- 		OnHitVoiceLines = {},
-- 		GiftGivenVoiceLines = {
-- 			{
-- 				Cue = "/VO/MelinoeField_2396",
-- 				Text = "I'm most grateful... and wish I could stay for the festivities.",
-- 				PlayFromTarget = true,
-- 				BreakIfPlayed = true,
-- 				PreLineWait = 1,
-- 			},
-- 		},
-- 		InteractVoiceLines = {},
-- 		NarrativeContextArtFlippable = false,
-- 		AttachedAnimationName = "MedeaGlow",
-- 	}
-- 	if params.OnUsedFunctionArgs then
-- 		local addToBase = {
-- 			OnUsedFunctionArgs = {
-- 				PreserveContextArt = true,
-- 				SkipInteractAnim = true,
-- 				SkipSound = true,
-- 				PackageName = "NPC_" .. npcName .. "_01",
-- 				ResetUseText = true,
-- 			},
-- 		}

-- 		for k, v in pairs(addToBase) do
-- 			baseGod[k] = v
-- 		end
-- 	end

-- 	local lowGodType = string.lower(godType)

-- 	for k, v in pairs(params) do
-- 		baseGod[k] = v
-- 	end

-- 	registerEntityData(npcName, lowGodType, baseGod)
-- end
--#endregion

--#region selene
-- Selene type shi
--* Too many functions run on the fact that there is only one "SpellDrop" - even if I add a spell lib there are a lot of functions that need to be reworked.
-- function public.InitializeSpellGod(spellName, params)
-- 	if not modstate.initialized then
-- 		rom.log.error("You must first Initialize your plugin guid, please use `GodsAPI.Initialize`")
-- 	end

-- 	local baseSpellDrop = {
-- 		-- GameStateRequirements handled in RunProgress table
-- 		Name = "SpellDrop",
-- 		TraitIndex = nil,
-- 		InheritFrom = nil,

-- 		OnUsedFunctionName = "OpenSpellScreen",
-- 		SpawnSound = "/SFX/SeleneMoonDrop",
-- 		ConsumeSound = "/SFX/SeleneMoonPickup",

-- 		DoorIcon = "SpellDropPreview",
-- 		UseText = "UseSpellDrop",
-- 		UseTextTalkAndGift = "UseLootAndGift",
-- 		UseTextTalkAndSpecial = "UseLootAndSpecial",
-- 		UseTextTalkGiftAndSpecial = "UseLootGiftAndSpecial",
-- 		BlockedLootInteractionText = "UseLootLocked",
-- 		ManualRecordUse = true,
-- 		CanReceiveGift = true,
-- 		RequireUseToGift = true,
-- 		AlwaysShowDefaultUseText = true,
-- 		BlockExitText = "ExitBlockedByMoney",
-- 		PlayInteract = true,
-- 		HideWorldText = true,
-- 		ExitUnlockDelay = 1.1,
-- 		TextLinesIgnoreQuests = true,
-- 		BoonInfoTitleText = "Codex_BoonInfo_Selene",
-- 		SubtitleColor = Color.SeleneVoice,
-- 		SurfaceShopText = "SpellDrop_Store",
-- 		SurfaceShopIcon = "SpellDropPreview",
-- 		AnimOffsetZ = 100,
-- 		ReplaceSpecialForGoldify = true,
-- 		GoldifyValue = 500,
-- 		GoldConversionEligible = true,
-- 		ResourceCosts = {
-- 			Money = 100,
-- 		},
-- 		SetupEvents = {
-- 			{
-- 				FunctionName = "PregenerateSpells",
-- 			},
-- 		},
-- 		ConfirmSound = "/Leftovers/Menu Sounds/EmoteThoughtful",
-- 		Color = { 100, 25, 255, 255 },
-- 		LightingColor = { 100, 25, 255, 255 },
-- 		LootColor = { 100, 25, 255, 255 },
-- 		PortraitEnterSound = "/SFX/Menu Sounds/LegendaryBoonShimmer",
-- 		SpeakerName = "Selene",
-- 		Speaker = "NPC_Selene_01",
-- 		LoadPackages = { "Selene" },
-- 		Portrait = "Portrait_Selene_Default_01",
-- 		NarrativeContextArt = "DialogueBackground_Moon",
-- 		SuperSacrificeCombatText = "SuperSacrifice_CombatText_SeleneUpgrade",
-- 		Gender = "F",
-- 		FlavorTextIds = {
-- 			"SpellDrop_FlavorText01",
-- 			"SpellDrop_FlavorText02",
-- 			"SpellDrop_FlavorText03",
-- 		},
-- 		SpecialInteractFunctionName = "SpecialInteractSalute",
-- 		SpecialInteractGameStateRequirements = {
-- 			{
-- 				PathTrue = { "GameState", "UseRecord", "SpellDrop" },
-- 			},
-- 		},
-- 		SpecialInteractCooldown = 60,
-- 		InteractVoiceLines = {
-- 			{ GlobalVoiceLines = "SeleneSaluteLines" },
-- 		},
-- 		PickupFunctionName = "SpellDropInteractPresentation",
-- 		PickupVoiceLines = {},
-- 		FirstSpawnVoiceLines = {},
-- 		OnSpawnVoiceLines = {},
-- 		UpgradeMenuOpenVoiceLines = {},
-- 		InteractTextLineSets = {},
-- 		GiftTextLineSets = {},
-- 		GiftGivenVoiceLines = {},
-- 		UsingInPortraitPackage = { "DialogueBackground_Moon_In" },
-- 	}

-- 	for k, v in pairs(params or {}) do
-- 		baseSpellDrop[k] = v
-- 	end

-- 	table.insert(queueToAdd, {
-- 		entityName = spellName,
-- 		entityType = "spell",
-- 		entityData = baseSpellDrop,
-- 	})
-- end
--#endregion

--#region portrait in person?
-- {
-- 	Name = "Portrait_Apollo_InPerson_01"
-- 	InheritFrom = "Portrait_Base_01"
--     FilePath = "Portraits\Apollo\Portraits_Apollo_01"
--  OffsetX = 0
-- 	EndFrame = 1
-- 	StartFrame = 1
-- 	CreateAnimations = [
-- 		{ Name = "Portrait_Apollo_OlympianGlow_In" }
-- 		{ Name = "Portrait_Apollo_Wiggle1_In" }
-- 		{ Name = "Portrait_Apollo_Wiggle2_In" }
-- 		{ Name = "Portrait_Apollo_StringsGlow"}
-- 		{ Name = "Portrait_Apollo_MainGlow"}
-- 		{ Name = "Portrait_Apollo_GlowArrow"}
-- 		{ Name = "Portrait_Apollo_Glint" }
-- 		{ Name = "Portrait_Apollo_Blink" }
-- 	]
-- }
-- {
-- 	Name = "Portrait_Apollo_InPerson_01_Exit"
-- 	InheritFrom = "Portrait_Base_01_Exit"
-- 	FilePath = "Portraits\Apollo\Portraits_Apollo_01"
-- 	EndFrame = 1
-- 	StartFrame = 1
-- }
-- {
-- 	Name = "Portrait_Apollo_InPerson_Serious_01"
-- 	InheritFrom = "Portrait_Apollo_InPerson_01"
-- 	FilePath = "Portraits\Apollo\Portraits_Apollo_Serious_01"
-- }
-- {
-- 	Name = "Portrait_Apollo_InPerson_Serious_01_Exit"
-- 	InheritFrom = "Portrait_Apollo_InPerson_01_Exit"
-- 	FilePath = "Portraits\Apollo\Portraits_Apollo_Serious_01"
-- }

--     	{
-- 	Name = "ApolloOverlay"
-- 	InheritFrom = "HadesOverlay"
-- 	FilePath = "Portraits\Apollo\Portraits_Apollo_Serious_01"
-- 	OffsetX = 150
-- 	OffsetY = 240
-- }

--#endregion
